<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Check your email for further instructions' => 'Перевірте поштову скриньку щоб продовжити',
    'Follow the link below to reset your password' => 'Перейдіть за посиланням щоб скинути Ваш пароль',
    'Follow the link below to verify your email' => 'Перейдіть за посиланням щоб підтвердити Ваш email',
    'Hello' => 'Вітаємо',
    'If you forgot your password you can' => 'Якщо Ви забули пароль можна',
    'Login' => 'Увійти',
    'Need new verification email' => 'Потрібен ще один лист підтвердження',
    'New password saved' => 'Новий пароль збережено',
    'OR' => 'АБО',
    'Password' => 'Пароль',
    'Password reset for' => 'Скинути пароль для',
    'Please confirm that you are not a robot' => 'Будь ласка, підтвердіть, що Ви не робот',
    'Please fill out your email. A link to reset password will be sent there' => 'Будь ласка, введіть Ваш email. Посилання щоб скинути пароль буде надіслано туди',
    'Please fill out your email. A verification email will be sent there' => 'Будь ласка, введіть Ваш email. Посилання щоб підтвердити поштову скриньку буде надіслано туди',
    'Remember Me' => 'Запам`ятати мене',
    'Repeat Password' => 'Повторіть пароль',
    'Resend' => 'Переслати',
    'Send' => 'Надіслати',
    'Sign up' => 'Реєстрація',
    'Sorry, we are unable to process request for the provided email address' => 'Вибачте, ми не змогли виконати Ваш запит для наданого email',
    'Sorry, we are unable to verify your account with provided token' => 'Вибачте, ми не змогли підтвердити акаунт за допомогою наданої інформації',
    'Status' => 'Статус',
    'Thank you for registration. Please check your inbox for verification email' => 'Дякую за реєстрацію. Будь ласка, перевірте Вашу поштову скриньку щоб підтвердити email',
    'This email address has already been taken' => 'Цей email вже зареєстровано',
    'Unexpected issue occured. Signup/login was not successfull, sorry' => 'Сталась неочікувана помилка. Реєстрація/вхід не були успішними, вибачте',
    'User was not created. Please, contact support' => 'Користувач не був створений. Будь ласка, зверніться до підтримки',
    'Via' => 'За допомогою',
    'Welcome' => 'Ласкаво просимо',
    'Your email address' => 'Ваш email',
    'Your email has been confirmed' => 'Ваш email підтверджено',
    'reset it' => 'скинути його',
    'Please choose your new password' => 'Будь ласка, створіть новий пароль',
    'Reset password' => 'Скинути пароль',
    'Save' => 'Зберегти',
];
