<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Check your email for further instructions' => 'Проверьте почтовый ящик чтобы продолжить',
    'Follow the link below to reset your password' => 'Пройдите по ссылке ниже чтобы спросить пароль',
    'Follow the link below to verify your email' => 'Пройдите по ссылке ниже чтобы подтвердить почту',
    'Hello' => 'Здравствуйте',
    'If you forgot your password you can' => 'Если Вы забыли пароль можно',
    'Login' => 'Войти',
    'Need new verification email' => 'Нужно еще одно письмо подтверждения',
    'New password saved' => 'Новый пароль сохранен',
    'OR' => 'ИЛИ',
    'Password' => 'Пароль',
    'Password reset for' => 'Сброс пароля для',
    'Please choose your new password' => 'Пожалуйста, создайте новый пароль',
    'Please confirm that you are not a robot' => 'Пожалуйста, подтвердите, что Вы не робот',
    'Please fill out your email. A link to reset password will be sent there' => 'Пожалуйста, введите свой email. Ссылка для сброса пароля будет отправлена туда',
    'Please fill out your email. A verification email will be sent there' => 'Пожалуйста, введите свой email. Ссылка для подтверждения почтового ящика будет отправлена туда',
    'Remember Me' => 'Запомнить меня',
    'Repeat Password' => 'Повторите пароль',
    'Resend' => 'Переслать',
    'Reset password' => 'Сбросить пароль',
    'Save' => 'Сохранить',
    'Send' => 'Отправить',
    'Sign up' => 'Зарегистрироваться',
    'Sorry, we are unable to process request for the provided email address' => 'Простите, мы не смогли выполнить Ваш запрос для предоставленного email',
    'Sorry, we are unable to verify your account with provided token' => 'Простите, мы не можем подтвердить Ваш аккаунт по предоставленным данным',
    'Status' => 'Статус',
    'Thank you for registration. Please check your inbox for verification email' => 'Спасибо за регистрацию. Пожалуйста, проверьте Ваш почтовый ящик чтобы подтвердить email',
    'This email address has already been taken' => 'Этот email уже зарегистрирован',
    'Unexpected issue occured. Signup/login was not successfull, sorry' => 'Случилась неожиданная ошибка. Регистрация/вход не были успешными, простите',
    'User was not created. Please, contact support' => 'Пользователь не был создан. Пожалуйста, обратитесь в поддержку',
    'Via' => 'При помощи',
    'Welcome' => 'Добро пожаловать',
    'Your email address' => 'Ваш email',
    'Your email has been confirmed' => 'Ваш email подтвержден',
    'reset it' => 'сбросить его',
    'Resend verification email' => 'Переслать письмо подтверждения',
];
